### ISSUE TITLE
HTTP Error 502: Bad Gateway, please check the datasource and pmproxy settings. To use this data source, please configure the URL in the query editor.

### ISSUE THREAD

**Issue by 307105141** [performancecopilot/grafana-pcp#23] opened 2019-11-09 02:32 UTC
Install version 6.3, but configure the data source to report an error:
HTTP Error 502: Bad Gateway, please check the datasource and pmproxy settings. To use this data source, please configure the URL in the query editor.

Do you have a successful case to share.
According to the Red Book installation deployment, but it has not been able to.

**Comment by andreasgerstmayr** [comment] 2019-11-12 16:34
@307105141: can you double-check if the URL field contains a value (i.e. move the cursor inside), and check if pmproxy is running and listening on the specified port? (e.g. sudo ss -lntp and check the Local Address:Port column)

**Comment by ConanScott** [comment] 2019-12-14 23:14
I'm afraid I have the same issue. Pmproxy is running and listening on 44322 on all interfaces and my data source url is populated (the text is white, not gray)

**Comment by andreasgerstmayr** [comment] 2019-12-20 13:35
@ConanScott: are you running Grafana in a container?
Try `curl -v http://[pmproxy-host]:44322` (replace `[pmproxy-host]` with the actual hostname/IP) from the same machine (or container) where Grafana is running.

You can also try "Access: Browser" in the data source settings, then your browser will directly connect to pmproxy.

**Comment by ConanScott** [comment] 2019-12-20 14:30
Thanks @andreasgerstmayr . I should have mentioned that I've done that sort of testing. Everything is conducted locally and I'm not using containers for anything. I have a whole bunch of services on this machine and networking hasn't been an issue. I also tried Access: Browser in Grafana with the same error being thrown. Seems I might have an issue with pmproxy itself. 

I don't see any similar issues on the pcp github or the wider web though. Perhaps I'll open an issue over there to see if someone can help.

Thanks for your great work. I look forward to getting this up and running.

```
curl -v http://192.168.0.4:44322
*   Trying 192.168.0.4:44322...
* TCP_NODELAY set
* Connected to 192.168.0.4 (192.168.0.4) port 44322 (#0)
> GET / HTTP/1.1
> Host: 192.168.0.4:44322
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

Thor:~$ sudo tail /var/log/pcp/pmproxy/pmproxy.log
Log for pmproxy on Thor started Sun Dec 15 21:14:07 2019

pmproxy: PID = 1670, PDU version = 2, user = pcp (997)
pmproxy request port(s):
  sts fd   port  family address
  === ==== ===== ====== =======
  ok     0 44322 inet   INADDR_ANY

Thor:~$ netstat -an | grep 44322
tcp        0      0 0.0.0.0:44322           0.0.0.0:*               LISTEN 
```

**Comment by andreasgerstmayr** [comment] 2019-12-20 17:23
@ConanScott, thanks for the detailed anaysis!
That's weird, pmproxy is listening but not responding to requests. Is this the latest version of PCP (5.0.2)? Could there be a firewall issue?

You can also try running pmproxy in the foreground, with http debugging turned on:
```
/usr/libexec/pcp/bin/pmproxy -f -l- -Dhttp
```
and attach `strace` to it.

**Comment by ConanScott** [comment] 2019-12-20 18:38
@andreasgerstmayr Thanks again. I don't _think_ I've got a firewall issue here. Everything is on the same host and I'm certainly able to make a socket connection. The only firewall rules active there are some added by the fail2ban recidive filter but they are all remote. Seems I have version 4.3.4 currently as it's the latest in the Ubuntu 19.10 repo. I'll see if I can find appropriate packages for 5.0

Here's the strace output when I try to do a Save and Test on the PCP bpftrace data source and Grafana. Looks like pmproxy just closes the door

```
Thor:~$ sudo strace -p 6963
strace: Process 6963 attached
select(4, [3], NULL, NULL, NULL)        = 1 (in [3])
accept(3, {sa_family=AF_INET, sin_port=htons(34966), sin_addr=inet_addr("192.168.0.4")}, [112->16]) = 4
recvfrom(4, "G", 1, 0, NULL, NULL)      = 1
recvfrom(4, "E", 1, 0, NULL, NULL)      = 1
recvfrom(4, "T", 1, 0, NULL, NULL)      = 1
recvfrom(4, " ", 1, 0, NULL, NULL)      = 1
recvfrom(4, "/", 1, 0, NULL, NULL)      = 1
recvfrom(4, "p", 1, 0, NULL, NULL)      = 1
recvfrom(4, "m", 1, 0, NULL, NULL)      = 1
recvfrom(4, "a", 1, 0, NULL, NULL)      = 1
recvfrom(4, "p", 1, 0, NULL, NULL)      = 1
recvfrom(4, "i", 1, 0, NULL, NULL)      = 1
recvfrom(4, "/", 1, 0, NULL, NULL)      = 1
recvfrom(4, "c", 1, 0, NULL, NULL)      = 1
recvfrom(4, "o", 1, 0, NULL, NULL)      = 1
recvfrom(4, "n", 1, 0, NULL, NULL)      = 1
recvfrom(4, "t", 1, 0, NULL, NULL)      = 1
recvfrom(4, "e", 1, 0, NULL, NULL)      = 1
recvfrom(4, "x", 1, 0, NULL, NULL)      = 1
recvfrom(4, "t", 1, 0, NULL, NULL)      = 1
recvfrom(4, "?", 1, 0, NULL, NULL)      = 1
recvfrom(4, "h", 1, 0, NULL, NULL)      = 1
recvfrom(4, "o", 1, 0, NULL, NULL)      = 1
recvfrom(4, "s", 1, 0, NULL, NULL)      = 1
recvfrom(4, "t", 1, 0, NULL, NULL)      = 1
recvfrom(4, "s", 1, 0, NULL, NULL)      = 1
recvfrom(4, "p", 1, 0, NULL, NULL)      = 1
recvfrom(4, "e", 1, 0, NULL, NULL)      = 1
recvfrom(4, "c", 1, 0, NULL, NULL)      = 1
recvfrom(4, "=", 1, 0, NULL, NULL)      = 1
recvfrom(4, "1", 1, 0, NULL, NULL)      = 1
recvfrom(4, "2", 1, 0, NULL, NULL)      = 1
recvfrom(4, "7", 1, 0, NULL, NULL)      = 1
recvfrom(4, ".", 1, 0, NULL, NULL)      = 1
recvfrom(4, "0", 1, 0, NULL, NULL)      = 1
recvfrom(4, ".", 1, 0, NULL, NULL)      = 1
recvfrom(4, "0", 1, 0, NULL, NULL)      = 1
recvfrom(4, ".", 1, 0, NULL, NULL)      = 1
recvfrom(4, "1", 1, 0, NULL, NULL)      = 1
recvfrom(4, "&", 1, 0, NULL, NULL)      = 1
recvfrom(4, "p", 1, 0, NULL, NULL)      = 1
recvfrom(4, "o", 1, 0, NULL, NULL)      = 1
recvfrom(4, "l", 1, 0, NULL, NULL)      = 1
recvfrom(4, "l", 1, 0, NULL, NULL)      = 1
recvfrom(4, "t", 1, 0, NULL, NULL)      = 1
recvfrom(4, "i", 1, 0, NULL, NULL)      = 1
recvfrom(4, "m", 1, 0, NULL, NULL)      = 1
recvfrom(4, "e", 1, 0, NULL, NULL)      = 1
recvfrom(4, "o", 1, 0, NULL, NULL)      = 1
recvfrom(4, "u", 1, 0, NULL, NULL)      = 1
recvfrom(4, "t", 1, 0, NULL, NULL)      = 1
recvfrom(4, "=", 1, 0, NULL, NULL)      = 1
recvfrom(4, "3", 1, 0, NULL, NULL)      = 1
recvfrom(4, "0", 1, 0, NULL, NULL)      = 1
recvfrom(4, " ", 1, 0, NULL, NULL)      = 1
recvfrom(4, "H", 1, 0, NULL, NULL)      = 1
recvfrom(4, "T", 1, 0, NULL, NULL)      = 1
recvfrom(4, "T", 1, 0, NULL, NULL)      = 1
recvfrom(4, "P", 1, 0, NULL, NULL)      = 1
recvfrom(4, "/", 1, 0, NULL, NULL)      = 1
recvfrom(4, "1", 1, 0, NULL, NULL)      = 1
recvfrom(4, ".", 1, 0, NULL, NULL)      = 1
recvfrom(4, "1", 1, 0, NULL, NULL)      = 1
recvfrom(4, "\r", 1, 0, NULL, NULL)     = 1
close(4)                                = 0
```

And here's my current iptables

```
Thor:~$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
f2b-recidive  tcp  --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain f2b-recidive (1 references)
target     prot opt source               destination
REJECT     all  --  iserv.webzavod.ru    anywhere             reject-with icmp-port-unreachable
REJECT     all  --  60.190.224.130       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  197-248-10-108.safaricombusiness.co.ke  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  111.202.151.13       anywhere             reject-with icmp-port-unreachable
RETURN     all  --  anywhere             anywhere
```

**Comment by andreasgerstmayr** [comment] 2020-01-02 16:23
> Seems I have version 4.3.4 currently as it's the latest in the Ubuntu 19.10 repo. I'll see if I can find appropriate packages for 5.0

There was a **huge** amount of changes in pmproxy between version 4.3.4 and the latest version 5.0.2. It's likely that this issue was fixed already - could you please try with 5.0.2 (e.g. from https://bintray.com/pcp)?

**Comment by ConanScott** [comment] 2020-01-02 17:17
I haven't had much time to look at this but I tried the repo for Bionic (Ubuntu 18.04) and Buster before the holidays, but there are multiple dependency issues there for Ubuntu 19.04. I should have stuck with mainline Debian or stayed on the LTS version of Ubuntu I guess. 

I'll have to work out where to go from here, possibly building from source, but you can assume that issue is not on the PCP side for now I think. Possibly worth closing the issue, since the OP has never responded. Thanks again for your help.

**Comment by skyrocknroll** [comment] 2020-02-01 19:29
In ubuntu bionic `apt-get install pcp` install very old 4.0.1
```
echo "deb https://dl.bintray.com/pcp/bionic bionic main" | sudo tee -a /etc/apt/sources.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A51D3ADCDEA2C114
apt-get update
apt-get install pcp
```
The above steps worked

**Comment by chetanrjoshi777** [comment] 2020-02-15 00:17
Grafana server Version 6.6.1

Redis server v=5.0.3 

pcp version 5.0.2

Grafana pcp plugin - grafana-pcp-2.0.0-beta1

cat /proc/version
Linux version 4.9.0-8-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.130-2 (2018-10-27)

1. Installed the above packages and launched the browser <Server IP>:3000.
2. Added the plugin- Performance Co-pilot plugin.
3. Wanted to add data sources now- PCP Vector, PCP Redis.
4. While adding the data source(be it PCP vector or PCP Redis), entered http://localhost:44322 in the URL tab. Did not change any other settings and selected "Save and Test". Got this error message:

"HTTP Error 502: Bad Gateway, please check the datasource and pmproxy settings"

5. Not sure how to proceed further. Can you please help?

**Comment by andreasgerstmayr** [comment] 2020-02-17 13:24
@chetanrjoshi777: Can you check if pmproxy is running?

Please try the following commands:
`systemctl status pmproxy`
`cat /var/log/pcp/pmproxy/pmproxy.log`

**Comment by not4win** [comment] 2020-03-09 17:17
I had the exact same problem and restarting pmproxy process solved the issue for me. Try it
`sudo systemctl restart pmproxy`

**Comment by songjiao** [comment] 2020-03-10 15:48
had the same problem.
grafana 6.6.2

**Comment by mac133k** [comment] 2020-06-22 16:33
I think I have the same issue which I already posted on [StackOverflow](https://stackoverflow.com/questions/62518744/unable-to-use-pcp-vector-with-variable-target-host-in-grafana). However I am only getting 502 if I do not specify the URL in the data source settings or I override it in the graph settings. Even if I override it with the same URL as set in the data source params I get 502 or `Network error` in Grafana. Otherwise it works fine if the URL is set for the data source and not overridden in the graph settings. My Grafana is v7.0.0, PCP plugin v.1.0.1 and PCP v4.1.0 installed on target hosts (Centos7).

**Comment by mac133k** [comment] 2020-06-23 09:00
Actually my PCP plugin version was 2.0.2. I built it from source from the master branch today, but it did not fix the problem.

**Comment by natoscott** [comment] 2020-06-23 09:42
@mac133k you need PCP v5 or later to use grafana-pcp

**Comment by mac133k** [comment] 2020-06-23 10:33
@natoscott So you are suggesting that the problem is on PCP's site? Because the queries work fine if the URL is specified in the data source setting in Grafana. The problematic part is the URL override in the graph settings. Basically I can monitor one target host per data source and it cannot be changed on the dashboard.

**Comment by andreasgerstmayr** [comment] 2020-06-23 10:51
@mac133k : For the URL override setting you need to select access type = browser in the datasource settings (see https://grafana-pcp.readthedocs.io/en/latest/guides/multiple-vector-hosts.html).

If there are still issues, can you open the Web Developer Tools, go to the network tab, and inspect the requests?

**Comment by mac133k** [comment] 2020-06-23 12:05
@andreasgerstmayr I tried it in Browser mode before. So now that I checked the net console in my browser and the URL looked all right:

- the $host variable was translated to the IP address from the text box,
- the requests were sent to http://ip.ip.ip.ip:44323/pmapi,
- the params were `context context?hostspec=127.0.0.1&polltimeout=30`,
- the status code for every request was 200.

Despite all that Grafana shows no data and reports `Network error`. 

Also when I tried to add a test data source for a particular host the test failed in Browser mode giving the 502 error from the title of this thread. It only seems to work in Server mode for me.

**Comment by mac133k** [comment] 2020-06-23 12:08
I noticed many of these errors in the dev console:
```
SEC7123: [CORS] The origin 'http://<Grafana host IP>:3000' blocked a preflight request that failed to provide an Access-Control-Allow-Headers response header for a cross-origin request to 'http://<target host IP>:44323/pmapi/context?hostspec=127.0.0.1&polltimeout=30'.
```
I am not sure how does this relate to the main issue though.

**Comment by andreasgerstmayr** [comment] 2020-06-23 17:10
> I noticed many of these errors in the dev console:
> 
> ```
> SEC7123: [CORS] The origin 'http://<Grafana host IP>:3000' blocked a preflight request that failed to provide an Access-Control-Allow-Headers response header for a cross-origin request to 'http://<target host IP>:44323/pmapi/context?hostspec=127.0.0.1&polltimeout=30'.
> ```
> 
> I am not sure how does this relate to the main issue though.

That's the main issue.

In server mode, CORS is not required, because Grafana proxies all requests. In Browser mode, the browser is accessing pmproxy directly. Due to the way browsers work (same origin policy), browsers use CORS to verify if this request should be allowed or not [1].

PCP version 5.1.0+ is required (see commit: https://github.com/performancecopilot/pcp/commit/df2426ac8a815e8784a5159d1e633eef6816aaf4)


[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by mac133k** [comment] 2020-06-23 18:13
I see, thanks for the clarification.

**Comment by mac133k** [comment] 2020-06-24 09:33
Note to those who are stuck with PCP v4.X: the PCP Vector data source works fine in the Browser mode with URL override in Grafana v. 6.6.2, but not in every web browser - works in Firefox, but not in MS Edge.

**Comment by andreasgerstmayr** [comment] 2020-09-14 19:13
Closed due to inactivity.

**Closed by andreasgerstmayr** 2020-09-14 19:13 UTC

**Comment by nyako** [comment] 2020-12-02 16:00
Stumbled in here because I had that exact "Connection reset by peer" problem described by @ConanScott above.

I'm running Ubuntu 20.04, but my version of pcp was built from source (the pcp package from 20.04's official repository did not have pmdabpftrace...).

```
# cat /etc/os-release | grep PRETTY_NAME
PRETTY_NAME="Ubuntu 20.04.1 LTS"

# pcp -V
pcp version 5.2.2

# cat /var/log/pcp/pmproxy/pmproxy.log 
Log for pmproxy on 518c32706e17 started Wed Dec  2 15:33:36 2020

pmproxy: PID = 5968, PDU version = 2, user = pcp (999)
pmproxy request port(s):
  sts fd   port  family address
  === ==== ===== ====== =======
  ok     0 44322 inet   INADDR_ANY
  ok     3 44322 ipv6   INADDR_ANY

# netstat -nlt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:44321           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:44322           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:4330            0.0.0.0:*               LISTEN     
tcp6       0      0 :::44321                :::*                    LISTEN     
tcp6       0      0 :::44322                :::*                    LISTEN     
tcp6       0      0 :::4330                 :::*                    LISTEN

# curl -v http://localhost:44322/
*   Trying 127.0.0.1:44322...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 44322 (#0)
> GET / HTTP/1.1
> Host: localhost:44322
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```
 
As it turns out, I missed out libuv in my build. And quite mysteriously, libpcp_mmv.so was missing too.

```
# ldd /usr/lib/pcp/bin/pmproxy 
	linux-vdso.so.1 (0x00007ffe3c961000)
	libpcp_web.so.1 => /lib/libpcp_web.so.1 (0x00007fcaa455f000)
	libpcp.so.3 => /lib/libpcp.so.3 (0x00007fcaa44b2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcaa42c0000)
	libpcp_pmda.so.3 => /lib/libpcp_pmda.so.3 (0x00007fcaa42a5000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcaa4156000)
	libssl3.so => /lib/x86_64-linux-gnu/libssl3.so (0x00007fcaa40f7000)
	libnss3.so => /lib/x86_64-linux-gnu/libnss3.so (0x00007fcaa3fa6000)
	libnspr4.so => /lib/x86_64-linux-gnu/libnspr4.so (0x00007fcaa3f66000)
	libsasl2.so.2 => /lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007fcaa3f49000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcaa3f26000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fcaa3f20000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcaa45c7000)
	libnssutil3.so => /lib/x86_64-linux-gnu/libnssutil3.so (0x00007fcaa3eed000)
	libplc4.so => /lib/x86_64-linux-gnu/libplc4.so (0x00007fcaa3ee4000)
	libplds4.so => /lib/x86_64-linux-gnu/libplds4.so (0x00007fcaa3edf000)
```
Recompiling with libuv1-dev on Ubuntu 20.04 solved the "Connection reset  by peer" problem for me. Hope this helps the next person who stumbles in with the same issue. 

(This isn't a grafana-pcp issue per say, but I landed here because I wanted to test-drive bpftrace through grafana-pcp.)

> Thanks @andreasgerstmayr . I should have mentioned that I've done that sort of testing. Everything is conducted locally and I'm not using containers for anything. I have a whole bunch of services on this machine and networking hasn't been an issue. I also tried Access: Browser in Grafana with the same error being thrown. Seems I might have an issue with pmproxy itself.
> 
> I don't see any similar issues on the pcp github or the wider web though. Perhaps I'll open an issue over there to see if someone can help.
> 
> Thanks for your great work. I look forward to getting this up and running.
> 
> ```
> curl -v http://192.168.0.4:44322
> *   Trying 192.168.0.4:44322...
> * TCP_NODELAY set
> * Connected to 192.168.0.4 (192.168.0.4) port 44322 (#0)
> > GET / HTTP/1.1
> > Host: 192.168.0.4:44322
> > User-Agent: curl/7.65.3
> > Accept: */*
> > 
> * Recv failure: Connection reset by peer
> * Closing connection 0
> curl: (56) Recv failure: Connection reset by peer
> 
> Thor:~$ telnet 192.168.0.4 44322
> Trying 192.168.0.4...
> Connected to 192.168.0.4.
> Escape character is '^]'.
> 
> Thor:~$ sudo tail /var/log/pcp/pmproxy/pmproxy.log
> Log for pmproxy on Thor started Sun Dec 15 21:14:07 2019
> 
> pmproxy: PID = 1670, PDU version = 2, user = pcp (997)
> pmproxy request port(s):
>   sts fd   port  family address
>   === ==== ===== ====== =======
>   ok     0 44322 inet   INADDR_ANY
> 
> Thor:~$ netstat -an | grep 44322
> tcp        0      0 0.0.0.0:44322           0.0.0.0:*               LISTEN 
> ```

**Comment by GavinTian1991** [comment] 2021-04-27 23:57
> Stumbled in here because I had that exact "Connection reset by peer" problem described by @ConanScott above.
> 
> I'm running Ubuntu 20.04, but my version of pcp was built from source (the pcp package from 20.04's official repository did not have pmdabpftrace...).
> 
> ```
> # cat /etc/os-release | grep PRETTY_NAME
> PRETTY_NAME="Ubuntu 20.04.1 LTS"
> 
> # pcp -V
> pcp version 5.2.2
> 
> # cat /var/log/pcp/pmproxy/pmproxy.log 
> Log for pmproxy on 518c32706e17 started Wed Dec  2 15:33:36 2020
> 
> pmproxy: PID = 5968, PDU version = 2, user = pcp (999)
> pmproxy request port(s):
>   sts fd   port  family address
>   === ==== ===== ====== =======
>   ok     0 44322 inet   INADDR_ANY
>   ok     3 44322 ipv6   INADDR_ANY
> 
> # netstat -nlt
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State      
> tcp        0      0 0.0.0.0:44321           0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:44322           0.0.0.0:*               LISTEN     
> tcp        0      0 0.0.0.0:4330            0.0.0.0:*               LISTEN     
> tcp6       0      0 :::44321                :::*                    LISTEN     
> tcp6       0      0 :::44322                :::*                    LISTEN     
> tcp6       0      0 :::4330                 :::*                    LISTEN
> 
> # curl -v http://localhost:44322/
> *   Trying 127.0.0.1:44322...
> * TCP_NODELAY set
> * Connected to localhost (127.0.0.1) port 44322 (#0)
> > GET / HTTP/1.1
> > Host: localhost:44322
> > User-Agent: curl/7.68.0
> > Accept: */*
> > 
> * Recv failure: Connection reset by peer
> * Closing connection 0
> curl: (56) Recv failure: Connection reset by peer
> ```
> 
> As it turns out, I missed out libuv in my build. And quite mysteriously, libpcp_mmv.so was missing too.
> 
> ```
> # ldd /usr/lib/pcp/bin/pmproxy 
> 	linux-vdso.so.1 (0x00007ffe3c961000)
> 	libpcp_web.so.1 => /lib/libpcp_web.so.1 (0x00007fcaa455f000)
> 	libpcp.so.3 => /lib/libpcp.so.3 (0x00007fcaa44b2000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcaa42c0000)
> 	libpcp_pmda.so.3 => /lib/libpcp_pmda.so.3 (0x00007fcaa42a5000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcaa4156000)
> 	libssl3.so => /lib/x86_64-linux-gnu/libssl3.so (0x00007fcaa40f7000)
> 	libnss3.so => /lib/x86_64-linux-gnu/libnss3.so (0x00007fcaa3fa6000)
> 	libnspr4.so => /lib/x86_64-linux-gnu/libnspr4.so (0x00007fcaa3f66000)
> 	libsasl2.so.2 => /lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007fcaa3f49000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcaa3f26000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fcaa3f20000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007fcaa45c7000)
> 	libnssutil3.so => /lib/x86_64-linux-gnu/libnssutil3.so (0x00007fcaa3eed000)
> 	libplc4.so => /lib/x86_64-linux-gnu/libplc4.so (0x00007fcaa3ee4000)
> 	libplds4.so => /lib/x86_64-linux-gnu/libplds4.so (0x00007fcaa3edf000)
> ```
> 
> Recompiling with libuv1-dev on Ubuntu 20.04 solved the "Connection reset by peer" problem for me. Hope this helps the next person who stumbles in with the same issue.
> 
> (This isn't a grafana-pcp issue per say, but I landed here because I wanted to test-drive bpftrace through grafana-pcp.)
> 
> > Thanks @andreasgerstmayr . I should have mentioned that I've done that sort of testing. Everything is conducted locally and I'm not using containers for anything. I have a whole bunch of services on this machine and networking hasn't been an issue. I also tried Access: Browser in Grafana with the same error being thrown. Seems I might have an issue with pmproxy itself.
> > I don't see any similar issues on the pcp github or the wider web though. Perhaps I'll open an issue over there to see if someone can help.
> > Thanks for your great work. I look forward to getting this up and running.
> > ```
> > curl -v http://192.168.0.4:44322
> > *   Trying 192.168.0.4:44322...
> > * TCP_NODELAY set
> > * Connected to 192.168.0.4 (192.168.0.4) port 44322 (#0)
> > > GET / HTTP/1.1
> > > Host: 192.168.0.4:44322
> > > User-Agent: curl/7.65.3
> > > Accept: */*
> > > 
> > * Recv failure: Connection reset by peer
> > * Closing connection 0
> > curl: (56) Recv failure: Connection reset by peer
> > 
> > Thor:~$ telnet 192.168.0.4 44322
> > Trying 192.168.0.4...
> > Connected to 192.168.0.4.
> > Escape character is '^]'.
> > 
> > Thor:~$ sudo tail /var/log/pcp/pmproxy/pmproxy.log
> > Log for pmproxy on Thor started Sun Dec 15 21:14:07 2019
> > 
> > pmproxy: PID = 1670, PDU version = 2, user = pcp (997)
> > pmproxy request port(s):
> >   sts fd   port  family address
> >   === ==== ===== ====== =======
> >   ok     0 44322 inet   INADDR_ANY
> > 
> > Thor:~$ netstat -an | grep 44322
> > tcp        0      0 0.0.0.0:44322           0.0.0.0:*               LISTEN 
> > ```

Hi, I came across the same issue and the log information looks similar. What do mean by saying "Recompiling with libuv1-dev". I have already install the libuv rpm package. Do I need to do add other option when I am building pcp from source code, following ./configure step? I think the pcp and grafana server version I used is not the problem to this issue. Thank you!

**Comment by andreasgerstmayr** [comment] 2021-04-28 12:46
> Hi, I came across the same issue and the log information looks similar. What do mean by saying "Recompiling with libuv1-dev". I have already install the libuv rpm package. Do I need to do add other option when I am building pcp from source code, following ./configure step? I think the pcp and grafana server version I used is not the problem to this issue. Thank you!

If you compile PCP from source, you need the `libuv-devel` package (on Fedora/RHEL/CentOS) or the `libuv1-dev` package (on Debian/Ubuntu).
After running `./configure`, make sure your `config.status` contains `S["HAVE_LIBUV"]="true"`.

**Comment by GavinTian1991** [comment] 2021-04-28 22:53
> > Hi, I came across the same issue and the log information looks similar. What do mean by saying "Recompiling with libuv1-dev". I have already install the libuv rpm package. Do I need to do add other option when I am building pcp from source code, following ./configure step? I think the pcp and grafana server version I used is not the problem to this issue. Thank you!
> 
> If you compile PCP from source, you need the `libuv-devel` package (on Fedora/RHEL/CentOS) or the `libuv1-dev` package (on Debian/Ubuntu).
> After running `./configure`, make sure your `config.status` contains `S["HAVE_LIBUV"]="true"`.

Hi andrea, it solved the problem and no more 'Recv failure: Connection reset by peer' jumped up. 
However, there is another problem which I need to solve ahead of time. I am following [instructions](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/monitoring_and_managing_system_status_and_performance/index#setting-up-pcp-on-a-system_setting-up-graphical-representation-of-pcp-metrics) here try to build up pcp with bpftrace data source shown on granafa. Under section "7.5. Setting up authentication between PCP components", I have already installed cyrus-sasl-scram cyrus-sasl-lib, the version is 2.1.27. The pcp version I used is 5.2.5 which support scram-sha-256 and my host is based on Centos 7.2. I created a user called jack and it showed such error:
 `pminfo -f -h "pcp://127.0.0.1?username=jack" disk.dev.read
pminfo: Cannot connect to PMCD on host "pcp://127.0.0.1?username=jack": Operation not supported`, which will also cause the data source adding failed on grafana by using pcp bpftrace plugins. Here are some logs which might concern about the issue:

`pcp verify --secure`
`== FAIL: pmcd(1) doesn't support secure sockets Check tutorials, verify NSS certificate database.`
`== FAIL: pmcd doesn't support user authentication Check tutorials, verify SASL configuration.`

`/usr/lib/pcp/bin/pmconfig -L unix_domain_sockets authentication`
`unix_domain_sockets=true authentication=false`

It seems like SASL authentication is not working and there might need to add some related ./configure options.
I know the issue is not quite related to the original gateway problem. I might still some help about it since I did not find some related information on google, or maybe open a new issue ticket not under this one.
really appreciate your help!

**Comment by andreasgerstmayr** [comment] 2021-05-04 15:38
Hi @GavinTian1991: yep, it would be better to open a new issue for that.

Regarding your issue, the error message shows that PCP wasn't compiled with secure sockets support. Did you install the SASL development package before compiling (`cyrus-sasl-devel`)? Probably it would be easier to use the precompiled packages of PCP (https://pcp.readthedocs.io/en/latest/HowTos/installation/index.html).

**Comment by GavinTian1991** [comment] 2021-05-11 01:15
> Hi @GavinTian1991: yep, it would be better to open a new issue for that.
> 
> Regarding your issue, the error message shows that PCP wasn't compiled with secure sockets support. Did you install the SASL development package before compiling (`cyrus-sasl-devel`)? Probably it would be easier to use the precompiled packages of PCP (https://pcp.readthedocs.io/en/latest/HowTos/installation/index.html).

Hi Andrea,
               sorry for the late reply, yes, I have already installed the SASL related package but still got the error. I just enable the script function but not using the authentication in order to test the whole function and it finally worked! Maybe something wrong with the SASL package version I used. really appreciate your help!
